# Generated by Django 4.0.4 on 2024-02-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOffer',
        ),
    ]
