# Generated by Django 4.0.4 on 2024-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_delete_courseoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachlor Degree'), ('Master', 'Master Degree')], max_length=25, null=True),
        ),
    ]
